# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weexDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for weexDemo
   pod 'WeexSDK', '~> 0.17.0'
   pod 'AFNetworking'
pod 'OHHTTPStubs', '~> 6.1.0'
  target 'weexDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
